--29.03.2017--

--Movies tasks--
USE movies
GO

--Task 1--
SELECT 
DISTINCT m.STUDIONAME, m.TITLE, s.ADDRESS, m.LENGTH
FROM MOVIE m
JOIN STUDIO s
ON m.STUDIONAME = s.NAME
WHERE m.STUDIONAME LIKE 'M%'
AND m.YEAR > 1980
GO

--Task 2--
SELECT m.NAME, m.ADDRESS, s.MOVIETITLE
FROM MOVIESTAR m
JOIN STARSIN s
ON m.NAME = s.STARNAME
WHERE m.NAME LIKE 'J%'
AND s.MOVIEYEAR > 1990
GO

--Task 3--
SELECT TITLE, YEAR, LENGTH
FROM MOVIE
WHERE LENGTH > 120
AND YEAR < 2000
OR LENGTH IS NULL
GO

--Task 4--
SELECT NAME, GENDER
FROM MOVIESTAR
WHERE NAME LIKE 'J%'
AND BIRTHDATE > 1948
ORDER BY NAME DESC
GO

--Task 5--
SELECT m.STUDIONAME, COUNT(*)
FROM MOVIE m
JOIN STARSIN s
ON m.TITLE = s.MOVIETITLE
GROUP BY m.STUDIONAME
GO

--Task 6--
SELECT 
	STARNAME, 
	COUNT(STARNAME) AS [Movies Count]
FROM STARSIN
GROUP BY STARNAME
GO

--Task 7--
SELECT m.STUDIONAME, m.TITLE, m.YEAR
FROM MOVIE m
INNER JOIN
( 
  SELECT MAX(YEAR) AS YEAR
  FROM MOVIE
  GROUP BY STUDIONAME
) AS m2
ON m.YEAR = m2.YEAR
ORDER BY m.YEAR DESC
GO

--Task 8--
SELECT m.NAME
FROM MOVIESTAR m
INNER JOIN
(
	SELECT MAX(BIRTHDATE) AS BIRTHDATE
	FROM MOVIESTAR
	WHERE GENDER = 'M'
) AS m2
ON m.BIRTHDATE = m2.BIRTHDATE
GO

--Task 9--
SELECT m1.STARNAME, m1.STUDIONAME, COUNT(*)
FROM MOVIE m
INNER JOIN
(
	SELECT m.STUDIONAME, m.TITLE, s.STARNAME
	FROM STARSIN s
	INNER JOIN MOVIE m
	ON s.MOVIETITLE = m.TITLE
) m1
ON m.TITLE = m1.TITLE
INNER JOIN
(
	SELECT s.STARNAME, COUNT(s.STARNAME) AS CNT
	FROM STARSIN s
	INNER JOIN MOVIE m
	ON s.MOVIETITLE = m.TITLE
	GROUP BY s.STARNAME
) m2
ON m1.STARNAME = m2.STARNAME
GROUP BY m1.STARNAME
GO

--Task 10--
SELECT m.TITLE AS movietitle, m.YEAR AS movieyear, m1.COUNT 
FROM MOVIE m
INNER JOIN
(
	SELECT COUNT(s.STARNAME) AS COUNT, s.MOVIETITLE
	FROM STARSIN s
	GROUP BY s.MOVIETITLE
	HAVING COUNT(s.STARNAME) > 2
) m1
ON m.TITLE = m1.MOVIETITLE
GO

--Ships Tasks--
USE ships
GO

--Task 1--
SELECT o.SHIP
FROM OUTCOMES o
WHERE o.SHIP LIKE 'C%'
OR o.SHIP LIKE 'K%'
GROUP BY o.SHIP
HAVING COUNT(o.SHIP) >= 1
GO

--Task 2--
SELECT DISTINCT s.NAME
FROM OUTCOMES o
RIGHT JOIN SHIPS s
ON o.SHIP = s.NAME
WHERE RESULT <> 'sunk'
OR RESULT IS NULL
GO